Fix issues found by pylint 2.4.4
Using pylint 2.4.4-1, the ionit tests are failing

======================================================================
FAIL: test_pylint (tests.test_pylint.PylintTestCase)
Test: Run pylint on Python source code
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest.AMGJfG/build.uFe/src/tests/test_pylint.py",
line 68, in test_pylint
    self.fail("\n".join(msgs))
AssertionError: pylint found issues:
************* Module ionit
/usr/bin/ionit:57:12: C0415: Import outside toplevel (warnings)
(import-outside-toplevel)
/usr/bin/ionit:60:16: C0415: Import outside toplevel (imp)
(import-outside-toplevel)'

The two import commands are used for backward compatibility. Therefore
disable the import-outside-toplevel warnings from pylint.

Closes: #946034
Signed-off-by: Benjamin Drung <benjamin.drung@cloud.ionos.com>